# Generated by Django 3.2.25 on 2025-02-22 13:18

from django.db import migrations, models
import projects.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanoramaImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='projects/%Y/%m/%d/')),
                ('date', models.CharField(max_length=20)),
                ('floor', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('position_z', models.FloatField(default=0.0)),
                ('front_x', models.FloatField(default=0.0)),
                ('front_y', models.FloatField(default=0.0)),
                ('front_z', models.FloatField(default=0.0)),
                ('sfm', models.CharField(max_length=10)),
                ('vt', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PanoramaLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('cm', models.CharField(blank=True, max_length=255, null=True)),
                ('contractor', models.CharField(blank=True, max_length=255, null=True)),
                ('designer', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=projects.models.project_image_upload_path)),
                ('start_date', models.DateField(verbose_name='공사 시작일')),
                ('end_date', models.DateField(verbose_name='공사 종료일')),
            ],
        ),
    ]
