# Generated by Django 3.2.25 on 2025-02-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='designer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
